name: Build TDLib (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (vcpkg)
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install zlib:x64-windows openssl:x64-windows readline:x64-windows

      - name: Install gperf (Chocolatey)
        run: choco install gperf -y

      - name: Configure and Build TDLib
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ^
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-build-windows
          path: build/
